### PR TITLE
Follow / Emotion cache, Some Fixes and Changes

### LINKED ISSUE #180: Need a api to get url meta infomation
For replacing front-end meta api feature. @FalseChord

### LINKED ISSUE #183: Project model types seem incorrect
https://github.com/readr-media/readr-restful/blob/6e318d7a1e4239d07ac82f64d3859948c1c056c8/models/projects.go#L16-L21

Since member id is now int64 and published_at is `datetime` in db schema, it's very weird both `UpdatedBy` and `PublishedAt` are `NullString`. 

Idea?  @FalseChord

### LINKED ISSUE #185: Tags API sort param need support text(tag_content)
GET `/tags?max_result=20&page=1&sort=text` is not work.

### LINKED ISSUE #186: Can not update post tags correctly
When we clean all tags in post, we request below

PUT `/post` with params
`"id":xxx,
"updated_by":xxx,
"tags": []`

but the data not update correctly. [High Priority]

### PR DESCRIPTION
**Pull request by FalseChord**
Functions:
1. Follow / Emotion cache, the cache now stores in Redis with the hash structure.
- Hash key format: "followcache_{emotion_type}"
  - "followcache_0" is following, "followcache_1" is like emotion ...
- Field key format: "{ResourceName}_{ResourceID}"
  - "post_1", "project_5566" ...
- The content in each field is a json-stringified _array_

Bug fixes:
1. Add go:site_map entry to Meta Info struct, this fix #180 .
2. Adjust variable types in models.Project struct, this fix #183 .
3. Resolve #186 with a new Nullable Int Slice type.
4. Map sort field "text" to "tag_content" in tag API, this might fix #185 .

Other little changes:
1. Export mail dialer initiator module for tests.
2. Remove some not-used code from comment.go.

### CODE REVIEW

File: routes/tag.go [hunk 1]
```diff
@@ -26,6 +26,9 @@ func (r *tagHandler) Get(c *gin.Context) {
 		c.JSON(http.StatusBadRequest, gin.H{"Error": "Bad Sorting Option"})
 		return
 	}
+	if args.Sorting == "text" {
+		args.Sorting = "tag_content"
+	}
```
Comment (ichiaohsu) [inline routes/tag.go]: If there are multiple sort settings like sort=tag_content,updated_at this wouldn't work, right?
